dist: bionic
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T otus_week_1/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulepota:$BINTRAY_API_KEY "https://api.bintray.com/content/lepota/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
